create or replace package sys.STANDARD is

    SUBTYPE TIME_UNCONSTRAINED IS DATE; --SUBTYPE TIME_UNCONSTRAINED IS TIME(9);
    SUBTYPE TIME_TZ_UNCONSTRAINED IS DATE; --SUBTYPE TIME_TZ_UNCONSTRAINED IS TIME(9) WITH TIME ZONE;

--    function ABS(D BINARY_DOUBLE) return BINARY_DOUBLE;
--    function ABS(F BINARY_FLOAT) return BINARY_FLOAT;
    function ABS(n NUMBER) return NUMBER;
    function ACOS(D BINARY_DOUBLE) return BINARY_DOUBLE;
    function ADD_MONTHS(LEFT DATE, RIGHT NUMBER) return DATE;
    function ADD_MONTHS(LEFT NUMBER, RIGHT DATE) return DATE;
    function ASIN(D BINARY_DOUBLE) return BINARY_DOUBLE;
    function ATAN(D BINARY_DOUBLE) return BINARY_DOUBLE;
    function ATAN2(x BINARY_DOUBLE, y BINARY_DOUBLE) return BINARY_DOUBLE;
    function BFILENAME(directory varchar2,filename varchar2) return BFILE;
    function BITAND(LEFT number, RIGHT number) return number;
    --function BITAND(LEFT pls_integer, RIGHT pls_integer) return pls_integer; -- mock to avoid too many
    function CEIL(D BINARY_DOUBLE) return BINARY_DOUBLE;
    function CEIL(F BINARY_FLOAT) return BINARY_FLOAT;
    function CEIL(n NUMBER) return NUMBER;
    function CHARTOROWID(str VARCHAR2) return ROWID;
    function CHR(n INTEGER) return varchar2;
    function COALESCE return VARCHAR2;
    function COMPOSE(ch VARCHAR2) return varchar2;
  --  function CONCAT(LEFT CLOB, RIGHT CLOB) return CLOB;
    function CONCAT(LEFT VARCHAR2, RIGHT VARCHAR2) return VARCHAR2;
    function CONVERT(src VARCHAR2, destcset VARCHAR2) return VARCHAR2;
    function CONVERT(src VARCHAR2, destcset VARCHAR2, srccset VARCHAR2) return VARCHAR2;
--    function CONVERT(SRCSTR CLOB, DSTCSN VARCHAR2) return CLOB;
--    function CONVERT(SRCSTR CLOB, DSTCSN VARCHAR2, SRCCSN VARCHAR2) return CLOB;
    function COS(D BINARY_DOUBLE) return BINARY_DOUBLE;
    function COS(N NUMBER) return NUMBER;
    function COSH(D BINARY_DOUBLE) return BINARY_DOUBLE;
    function COSH(N NUMBER) return NUMBER;
    function current_date return date;
   -- function current_time return TIME_TZ_UNCONSTRAINED;
    function current_timestamp return TIMESTAMP_TZ_UNCONSTRAINED;
    FUNCTION dbtimezone RETURN varchar2;
    function DECODE(expr DATE, pat DATE, res VARCHAR2) return VARCHAR2;
    function DECODE(expr DATE, pat DATE, res DATE) return DATE;
    function DECODE(expr DATE, pat DATE, res NUMBER) return NUMBER;
    function DECODE(expr NUMBER, pat NUMBER, res DATE) return DATE;
    function DECODE(expr NUMBER, pat NUMBER, res NUMBER) return NUMBER;
    function DECODE(expr NUMBER, pat NUMBER, res VARCHAR2) return VARCHAR2;
    function DECODE(expr VARCHAR2, pat VARCHAR2, res DATE) return DATE;
    function DECODE(expr VARCHAR2, pat VARCHAR2, res NUMBER) return NUMBER;
    function DECODE(expr VARCHAR2, pat VARCHAR2, res VARCHAR2) return VARCHAR2;
    function DECOMPOSE(ch VARCHAR2, canmode in VARCHAR2 DEFAULT 'CANONICAL') return varchar2;
    function EMPTY_BLOB return blob;
    function EMPTY_CLOB return clob;
    function EXP(D BINARY_DOUBLE) return BINARY_DOUBLE;
    function EXP(N NUMBER) return NUMBER;
    function FLOOR(D BINARY_DOUBLE) return BINARY_DOUBLE;
    function FLOOR(F BINARY_FLOAT) return BINARY_FLOAT;
    function FLOOR(n NUMBER) return NUMBER;
    FUNCTION from_tz(t TIMESTAMP_UNCONSTRAINED,timezone VARCHAR2) RETURN timestamp_tz_unconstrained;
    function GREATEST(pattern BINARY_DOUBLE) return BINARY_DOUBLE;
    function GREATEST(pattern BINARY_FLOAT) return BINARY_FLOAT;
    function GREATEST(pattern DATE) return DATE;
    function GREATEST(pattern DSINTERVAL_UNCONSTRAINED) return DSINTERVAL_UNCONSTRAINED;
    function GREATEST(pattern NUMBER) return NUMBER;
    --function GREATEST(pattern PLS_INTEGER) return PLS_INTEGER;
   -- function GREATEST(pattern TIME_TZ_UNCONSTRAINED) return TIME_TZ_UNCONSTRAINED;
    --function GREATEST(pattern TIME_UNCONSTRAINED) return TIME_UNCONSTRAINED;
    function GREATEST(pattern TIMESTAMP_LTZ_UNCONSTRAINED) return TIMESTAMP_LTZ_UNCONSTRAINED;
    function GREATEST(pattern TIMESTAMP_TZ_UNCONSTRAINED) return TIMESTAMP_TZ_UNCONSTRAINED;
    function GREATEST(pattern TIMESTAMP_UNCONSTRAINED) return TIMESTAMP_UNCONSTRAINED;
    function GREATEST(pattern VARCHAR2) return VARCHAR2;
    function GREATEST(pattern YMINTERVAL_UNCONSTRAINED) return YMINTERVAL_UNCONSTRAINED;
--    Function GREATEST_LB(pattern MLSLABEL) return MLSLABEL;
    function HEXTORAW(c VARCHAR2) return RAW;
    function INITCAP(ch VARCHAR2) return VARCHAR2;
    --function INSTR(STR1 CLOB, STR2 CLOB, POS INTEGER := 1, NTH INTEGER := 1) return INTEGER;
    function INSTR(STR1 VARCHAR2, STR2 VARCHAR2) return PLS_INTEGER; -- SS добавлено вручную
    function INSTR(STR1 VARCHAR2, STR2 VARCHAR2, POS PLS_INTEGER) return PLS_INTEGER; -- SS добавлено вручную
    function INSTR(STR1 VARCHAR2, STR2 VARCHAR2, POS PLS_INTEGER, NTH POSITIVE) return PLS_INTEGER; -- SS добавлено вручную
--    function INSTR(STR1 VARCHAR2, STR2 VARCHAR2, POS PLS_INTEGER := 1, NTH POSITIVE := 1) return PLS_INTEGER;
    function INSTR2(STR1 VARCHAR2, STR2 VARCHAR2, POS PLS_INTEGER := 1, NTH POSITIVE := 1) return PLS_INTEGER;
    function INSTR4(STR1 VARCHAR2, STR2 VARCHAR2, POS PLS_INTEGER := 1, NTH POSITIVE := 1) return PLS_INTEGER;
    --function INSTRB(STR1 CLOB, STR2 CLOB, POS INTEGER := 1, NTH INTEGER := 1) return INTEGER;
    function INSTRB(STR1 VARCHAR2, STR2 VARCHAR2, POS PLS_INTEGER := 1, NTH POSITIVE := 1) return PLS_INTEGER;
    function INSTRC(STR1 VARCHAR2, STR2 VARCHAR2, POS PLS_INTEGER := 1, NTH POSITIVE := 1) return PLS_INTEGER;
    function LAST_DAY(RIGHT DATE) return DATE;
    function LEAST(pattern BINARY_DOUBLE) return BINARY_DOUBLE;
    function LEAST(pattern BINARY_FLOAT) return BINARY_FLOAT;
    function LEAST(pattern DATE) return DATE;
    function LEAST(pattern DSINTERVAL_UNCONSTRAINED) return DSINTERVAL_UNCONSTRAINED;
    function LEAST(pattern NUMBER) return NUMBER;
    --function LEAST(pattern PLS_INTEGER) return PLS_INTEGER;
--    function LEAST(pattern TIME_TZ_UNCONSTRAINED) return TIME_TZ_UNCONSTRAINED;
--    function LEAST(pattern TIME_UNCONSTRAINED) return TIME_UNCONSTRAINED;
    function LEAST(pattern TIMESTAMP_LTZ_UNCONSTRAINED) return TIMESTAMP_LTZ_UNCONSTRAINED;
    function LEAST(pattern TIMESTAMP_TZ_UNCONSTRAINED) return TIMESTAMP_TZ_UNCONSTRAINED;
    function LEAST(pattern TIMESTAMP_UNCONSTRAINED) return TIMESTAMP_UNCONSTRAINED;
    function LEAST(pattern VARCHAR2) return VARCHAR2;
    function LEAST(pattern YMINTERVAL_UNCONSTRAINED) return YMINTERVAL_UNCONSTRAINED;
--    Function LEAST_UB(pattern MLSLABEL) return MLSLABEL;
    function LENGTH(bl BLOB) return integer;
    --function LENGTH(ch CLOB) return integer;
    function LENGTH(ch VARCHAR2) return natural;
    function LENGTH2(ch VARCHAR2) return natural;
    function LENGTH4(ch VARCHAR2) return natural;
    function LENGTHB(bl BLOB) return integer;
    --function LENGTHB(ch CLOB) return integer;
    function LENGTHB(ch VARCHAR2) return NUMBER;
    function LENGTHC(ch VARCHAR2) return natural;
    function LEVEL return NUMBER;
    function LN(D BINARY_DOUBLE) return BINARY_DOUBLE;
    function LN(N NUMBER) return NUMBER;
--    FUNCTION localtime RETURN time_unconstrained;
    FUNCTION localtimestamp RETURN timestamp_unconstrained;
    function LOG(LEFT BINARY_DOUBLE, RIGHT BINARY_DOUBLE) return BINARY_DOUBLE;
    function LOG(LEFT NUMBER, RIGHT NUMBER) return NUMBER;
    --function LOWER(ch CLOB) return CLOB;
    function LOWER(ch VARCHAR2) return VARCHAR2;
    --function LPAD(STR1 CLOB, LEN integer) return CLOB;
    --function LPAD(STR1 CLOB, LEN integer, PAD CLOB) return CLOB;
    function LPAD(STR1 VARCHAR2, LEN pls_integer) return VARCHAR2;
    function LPAD(STR1 VARCHAR2, LEN pls_integer, PAD VARCHAR2) return VARCHAR2;
    --function LTRIM(STR1 CLOB) return CLOB;
    --function LTRIM(STR1 CLOB, TSET CLOB) return CLOB;
    function LTRIM(STR1 VARCHAR2) return VARCHAR2;
    function LTRIM(STR1 VARCHAR2, TSET VARCHAR2) return VARCHAR2;
    function MOD(n1 NUMBER, n2 NUMBER) return NUMBER;
    function MONTHS_BETWEEN(LEFT DATE, RIGHT DATE) return NUMBER;
    function NANVL(d1 BINARY_DOUBLE, d2 BINARY_DOUBLE) return BINARY_DOUBLE;
    function NANVL(f1 BINARY_FLOAT, f2 BINARY_FLOAT) return BINARY_FLOAT;
    function NANVL(n1 NUMBER, n2 NUMBER) return NUMBER;
    function NCHARTOROWID(str NVARCHAR2) return ROWID;
    function NCHR(n integer) return NVARCHAR2;
--    function NEW_TIME(RIGHT DATE, MIDDLE VARCHAR2, LEFT VARCHAR2) return DATE;
    function NEXT_DAY(LEFT DATE, RIGHT VARCHAR2) return DATE;
    function NHEXTORAW(c NVARCHAR2) return RAW;
    function NLS_CHARSET_DECL_LEN(bytecnt NUMBER, csetid NUMBER) return PLS_INTEGER;
    function NLS_CHARSET_ID(csetname VARCHAR2) return PLS_INTEGER;
    function NLS_CHARSET_NAME(csetid PLS_INTEGER) return VARCHAR2;
    function NLS_LOWER(ch CLOB) return CLOB;
    function NLS_LOWER(ch CLOB, parms VARCHAR2) return CLOB;
    function NLS_UPPER(ch CLOB) return CLOB;
    function NLS_UPPER(ch CLOB, parms VARCHAR2) return CLOB;
    function NULLFN(str VARCHAR2) return RAW;
    function NULLIF(v1 BOOLEAN, v2 BOOLEAN) return BOOLEAN;
    function NULLIF(v1 VARCHAR2, v2 VARCHAR2) return VARCHAR2;
    function NUMTODSINTERVAL(numerator number, units varchar2) return DSINTERVAL_UNCONSTRAINED;
    function NUMTOYMINTERVAL(numerator number, units varchar2) return YMINTERVAL_UNCONSTRAINED;
    function NVL(B1 BOOLEAN, B2 BOOLEAN) return BOOLEAN;
    function NVL(b1 DSINTERVAL_UNCONSTRAINED, b2 DSINTERVAL_UNCONSTRAINED) return DSINTERVAL_UNCONSTRAINED;
--    function NVL(b1 TIME_TZ_UNCONSTRAINED, b2 TIME_TZ_UNCONSTRAINED) return TIME_TZ_UNCONSTRAINED;
--    function NVL(b1 TIME_UNCONSTRAINED, b2 TIME_UNCONSTRAINED) return TIME_UNCONSTRAINED;
    function NVL(b1 TIMESTAMP_LTZ_UNCONSTRAINED, b2 TIMESTAMP_LTZ_UNCONSTRAINED) return TIMESTAMP_LTZ_UNCONSTRAINED;
    function NVL(b1 TIMESTAMP_TZ_UNCONSTRAINED, b2 TIMESTAMP_TZ_UNCONSTRAINED) return TIMESTAMP_TZ_UNCONSTRAINED;
    function NVL(b1 TIMESTAMP_UNCONSTRAINED, b2 TIMESTAMP_UNCONSTRAINED) return TIMESTAMP_UNCONSTRAINED;
    function NVL(b1 YMINTERVAL_UNCONSTRAINED, b2 YMINTERVAL_UNCONSTRAINED) return YMINTERVAL_UNCONSTRAINED;
    function NVL(d1 DATE, d2 DATE) return DATE;
    function NVL(d1 BINARY_DOUBLE, d2 BINARY_DOUBLE) return BINARY_DOUBLE;
    function NVL(f1 BINARY_FLOAT, f2 BINARY_FLOAT) return BINARY_FLOAT;
--    function NVL(label1 MLSLABEL, label2 MLSLABEL) return MLSLABEL;
    function NVL(n1 NUMBER, n2 NUMBER) return NUMBER;
    --function NVL(s1 CLOB, s2 CLOB) return CLOB;
    function NVL(s1 VARCHAR2, s2 VARCHAR2) return VARCHAR2;
    function NVL(I1 PLS_INTEGER, I2 PLS_INTEGER) return PLS_INTEGER;
    function POWER(d BINARY_DOUBLE, e BINARY_DOUBLE) return BINARY_DOUBLE;
    function POWER(n NUMBER, e NUMBER) return NUMBER;
    function RAWTOHEX(r RAW) return VARCHAR2;
    function RAWTONHEX(r RAW) return NVARCHAR2;
    --function REGEXP_COUNT(srcstr CLOB, pattern VARCHAR2, position INTEGER := 1, modifier VARCHAR2 DEFAULT NULL) return INTEGER;
    function REGEXP_COUNT(srcstr VARCHAR2, pattern VARCHAR2) return PLS_INTEGER;
    function REGEXP_COUNT(srcstr VARCHAR2, pattern VARCHAR2, position PLS_INTEGER) return PLS_INTEGER;
    function REGEXP_COUNT(srcstr VARCHAR2, pattern VARCHAR2, position PLS_INTEGER, modifier VARCHAR2) return PLS_INTEGER;
    --function REGEXP_INSTR(srcstr CLOB, pattern VARCHAR2, position INTEGER := 1, occurrence INTEGER := 1, returnparam PLS_INTEGER := 0, modifier VARCHAR2 DEFAULT NULL, subexpression PLS_INTEGER := 0) return INTEGER;
    function REGEXP_INSTR(srcstr VARCHAR2, pattern VARCHAR2) return PLS_INTEGER;
    function REGEXP_INSTR(srcstr VARCHAR2, pattern VARCHAR2, position PLS_INTEGER) return PLS_INTEGER;
    function REGEXP_INSTR(srcstr VARCHAR2, pattern VARCHAR2, position PLS_INTEGER, occurrence PLS_INTEGER) return PLS_INTEGER;
    function REGEXP_INSTR(srcstr VARCHAR2, pattern VARCHAR2, position PLS_INTEGER, occurrence PLS_INTEGER, returnparam PLS_INTEGER) return PLS_INTEGER;
    function REGEXP_INSTR(srcstr VARCHAR2, pattern VARCHAR2, position PLS_INTEGER, occurrence PLS_INTEGER, returnparam PLS_INTEGER, modifier VARCHAR2) return PLS_INTEGER;
    function REGEXP_INSTR(srcstr VARCHAR2, pattern VARCHAR2, position PLS_INTEGER, occurrence PLS_INTEGER, returnparam PLS_INTEGER, modifier VARCHAR2, subexpression PLS_INTEGER) return PLS_INTEGER;
    --function REGEXP_LIKE(srcstr CLOB, pattern VARCHAR2, modifier VARCHAR2 DEFAULT NULL) return BOOLEAN;
    function REGEXP_LIKE(srcstr VARCHAR2, pattern VARCHAR2) return BOOLEAN;
    function REGEXP_LIKE(srcstr VARCHAR2, pattern VARCHAR2, modifier VARCHAR2) return BOOLEAN;
    --function REGEXP_REPLACE(srcstr CLOB, pattern VARCHAR2, replacestr CLOB DEFAULT NULL, position INTEGER := 1, occurrence INTEGER := 0, modifier VARCHAR2 DEFAULT NULL) return CLOB;
--    function REGEXP_REPLACE(srcstr CLOB, pattern VARCHAR2, replacestr VARCHAR2 DEFAULT NULL, position INTEGER := 1, occurrence INTEGER := 0, modifier VARCHAR2 DEFAULT NULL) return CLOB;
    function REGEXP_REPLACE(srcstr VARCHAR2, pattern VARCHAR2) return VARCHAR2;
    function REGEXP_REPLACE(srcstr VARCHAR2, pattern VARCHAR2, replacestr VARCHAR2) return VARCHAR2;
    function REGEXP_REPLACE(srcstr VARCHAR2, pattern VARCHAR2, replacestr VARCHAR2, position PLS_INTEGER) return VARCHAR2;
    function REGEXP_REPLACE(srcstr VARCHAR2, pattern VARCHAR2, replacestr VARCHAR2, position PLS_INTEGER, occurrence PLS_INTEGER) return VARCHAR2;
    function REGEXP_REPLACE(srcstr VARCHAR2, pattern VARCHAR2, replacestr VARCHAR2, position PLS_INTEGER, occurrence PLS_INTEGER, modifier VARCHAR2) return VARCHAR2;
    --function REGEXP_SUBSTR(srcstr CLOB, pattern VARCHAR2, position INTEGER := 1, occurrence INTEGER := 1, modifier VARCHAR2 DEFAULT NULL, subexpression PLS_INTEGER := 0) return CLOB;
    function REGEXP_SUBSTR(srcstr VARCHAR2, pattern VARCHAR2) return VARCHAR2;
    function REGEXP_SUBSTR(srcstr VARCHAR2, pattern VARCHAR2, position PLS_INTEGER) return VARCHAR2;
    function REGEXP_SUBSTR(srcstr VARCHAR2, pattern VARCHAR2, position PLS_INTEGER, occurrence PLS_INTEGER) return VARCHAR2;
    function REGEXP_SUBSTR(srcstr VARCHAR2, pattern VARCHAR2, position PLS_INTEGER, occurrence PLS_INTEGER, modifier VARCHAR2) return VARCHAR2;
    function REGEXP_SUBSTR(srcstr VARCHAR2, pattern VARCHAR2, position PLS_INTEGER, occurrence PLS_INTEGER, modifier VARCHAR2, subexpression PLS_INTEGER) return VARCHAR2;
    function REM(LEFT NUMBER, RIGHT NUMBER) return NUMBER;
    --function REPLACE(SRCSTR CLOB, OLDSUB CLOB, NEWSUB CLOB := NULL) return CLOB;
    function REPLACE(SRCSTR VARCHAR2, OLDSUB VARCHAR2) return VARCHAR2;
    function REPLACE(SRCSTR VARCHAR2, OLDSUB VARCHAR2, NEWSUB VARCHAR2) return VARCHAR2;
    --function ROUND(i pls_integer, places pls_integer := 0) return pls_integer; -- mock to avoid too many declarations
    --function ROUND(LEFT BINARY_DOUBLE) return BINARY_DOUBLE;
    --function ROUND(LEFT BINARY_FLOAT) return BINARY_FLOAT;
    function ROUND(LEFT NUMBER) return NUMBER;
    function ROUND(LEFT NUMBER, RIGHT pls_integer) return NUMBER;
    --function ROUND(LEFT DATE, RIGHT VARCHAR2) return DATE;
    --function ROUND(RIGHT DATE) return DATE;
    function ROWIDTOCHAR(str ROWID) return VARCHAR2;
    function ROWIDTONCHAR(str ROWID) return NVARCHAR2;
--    Function ROWLABEL return MLSLABEL;
    function ROWNUM return NUMBER;
    function RPAD(STR1 CLOB, LEN integer) return CLOB;
    function RPAD(STR1 CLOB, LEN integer, PAD CLOB) return CLOB;
    function RPAD(STR1 VARCHAR2, LEN pls_integer) return VARCHAR2;
    function RPAD(STR1 VARCHAR2, LEN pls_integer, PAD VARCHAR2) return VARCHAR2;
    --function RTRIM(STR1 CLOB) return CLOB;
    --function RTRIM(STR1 CLOB, TSET CLOB) return CLOB;
    function RTRIM(STR1 VARCHAR2) return VARCHAR2;
    function RTRIM(STR1 VARCHAR2, TSET VARCHAR2) return VARCHAR2;
    FUNCTION sessiontimezone RETURN varchar2;
    function SIGN(d BINARY_DOUBLE) return SIGNTYPE;
    function SIGN(f BINARY_FLOAT) return SIGNTYPE;
    --function SIGN(i PLS_INTEGER) return SIGNTYPE;
    function SIGN(n NUMBER) return SIGNTYPE;
    function SIN(D BINARY_DOUBLE) return BINARY_DOUBLE;
    function SIN(N NUMBER) return NUMBER;
    function SINH(D BINARY_DOUBLE) return BINARY_DOUBLE;
    function SINH(N NUMBER) return NUMBER;
    function SQLCODE return PLS_INTEGER;
    function SQLERRM(code PLS_INTEGER) return varchar2;
    function SQLERRM return varchar2;
    function SQRT(d BINARY_DOUBLE) return BINARY_DOUBLE;
    function SQRT(f BINARY_FLOAT) return BINARY_FLOAT;
    function SQRT(n NUMBER) return NUMBER;
    --function SUBSTR(STR1 CLOB, POS INTEGER, LEN INTEGER := 18446744073709551615) return CLOB;
    function SUBSTR(STR1 VARCHAR2, POS PLS_INTEGER) return VARCHAR2; -- SS добавлено вручную
    function SUBSTR(STR1 VARCHAR2, POS PLS_INTEGER, LEN PLS_INTEGER) return VARCHAR2;
--    function SUBSTR(STR1 VARCHAR2, POS PLS_INTEGER, LEN PLS_INTEGER := 2147483647) return VARCHAR2;
    function SUBSTR2(STR1 VARCHAR2, POS PLS_INTEGER, LEN PLS_INTEGER := 2147483647) return VARCHAR2;
    function SUBSTR4(STR1 VARCHAR2, POS PLS_INTEGER, LEN PLS_INTEGER := 2147483647) return VARCHAR2;
    --function SUBSTRB(STR1 CLOB, POS INTEGER, LEN INTEGER := 18446744073709551615) return CLOB;
    function SUBSTRB(STR1 VARCHAR2, POS PLS_INTEGER) return VARCHAR2;
    function SUBSTRB(STR1 VARCHAR2, POS PLS_INTEGER, LEN PLS_INTEGER) return VARCHAR2;
    function SUBSTRC(STR1 VARCHAR2, POS PLS_INTEGER, LEN PLS_INTEGER := 2147483647) return VARCHAR2;
--    function SYS_AT_TIME_ZONE(t time_tz_unconstrained, i varchar2) RETURN time_tz_unconstrained;
    function SYS_AT_TIME_ZONE(t timestamp_tz_unconstrained, i varchar2) RETURN timestamp_tz_unconstrained;
    function SYS_CONTEXT(namespace varchar2, attribute varchar2) return varchar2;
    function SYS_CONTEXT(namespace varchar2, attribute varchar2, newoptional varchar2) return varchar2;
    FUNCTION SYS_EXTRACT_UTC(t timestamp_tz_unconstrained) return TIMESTAMP_UNCONSTRAINED;
    function SYS_GUID return RAW;
    function SYS_LITERALTODATE(numerator varchar2) return DATE;
    function SYS_LITERALTODSINTERVAL(numerator varchar2, units varchar2) return DSINTERVAL_UNCONSTRAINED;
--    function SYS_LITERALTOTIME(numerator varchar2) return TIME_UNCONSTRAINED;
    function SYS_LITERALTOTIMESTAMP(numerator varchar2) return TIMESTAMP_UNCONSTRAINED;
--    function SYS_LITERALTOTZTIME(numerator varchar2) return TIME_TZ_UNCONSTRAINED;
    function SYS_LITERALTOTZTIMESTAMP(numerator varchar2) return TIMESTAMP_TZ_UNCONSTRAINED;
    function SYS_LITERALTOYMINTERVAL(numerator varchar2, units varchar2) return YMINTERVAL_UNCONSTRAINED;
    function SYSDATE return DATE;
    FUNCTION systimestamp RETURN timestamp_tz_unconstrained;
    function TAN(D BINARY_DOUBLE) return BINARY_DOUBLE;
    function TAN(N NUMBER) return NUMBER;
    function TANH(D BINARY_DOUBLE) return BINARY_DOUBLE;
    function TANH(N NUMBER) return NUMBER;
    function TO_ANYLOB(RIGHT VARCHAR2) return CLOB;
    function TO_BINARY_DOUBLE(LEFT VARCHAR2, FORMAT VARCHAR2) RETURN BINARY_DOUBLE;
    function TO_BINARY_DOUBLE(LEFT VARCHAR2, FORMAT VARCHAR2, PARMS VARCHAR2) RETURN BINARY_DOUBLE;
    function TO_BINARY_DOUBLE(RIGHT BINARY_DOUBLE) RETURN BINARY_DOUBLE;
    function TO_BINARY_FLOAT(LEFT VARCHAR2, FORMAT VARCHAR2) RETURN BINARY_FLOAT;
    function TO_BINARY_FLOAT(LEFT VARCHAR2, FORMAT VARCHAR2, PARMS VARCHAR2) RETURN BINARY_FLOAT;
    function TO_BINARY_FLOAT(RIGHT BINARY_FLOAT) RETURN BINARY_FLOAT;
    function TO_BLOB(RIGHT RAW) return BLOB;
    function TO_CHAR(left binary_double, format varchar2) return VARCHAR2;
    function TO_CHAR(left binary_float, format varchar2) return VARCHAR2;
    function TO_CHAR(LEFT DATE, RIGHT VARCHAR2) return VARCHAR2;
    function TO_CHAR(LEFT DATE) return VARCHAR2; -- SS добавлено вручную
    function TO_CHAR(LEFT NUMBER, RIGHT VARCHAR2) return VARCHAR2;
    function TO_CHAR(LEFT NUMBER) return VARCHAR2; -- SS добавлено вручную
    function TO_CHAR(RIGHT VARCHAR2) return VARCHAR2;
    Function TO_CHAR(label MLSLABEL, format VARCHAR2) return VARCHAR2; -- SS todo MLSLABEL мы не используем, конкретно здесь оставляем только чтобы разрешить конфликты сигнатур, нужно убрать после доработки транспайлера
    function TO_CHAR(left binary_double, format varchar2, parms varchar2) return varchar2;
    function TO_CHAR(left binary_float, format varchar2, parms varchar2) return varchar2;
    function TO_CHAR(left date, format varchar2, parms varchar2) return varchar2;
    function TO_CHAR(left DSINTERVAL_UNCONSTRAINED, format VARCHAR2) return VARCHAR2;
    function TO_CHAR(left DSINTERVAL_UNCONSTRAINED, format VARCHAR2, parms VARCHAR2) return VARCHAR2;
    function TO_CHAR(left number, format varchar2, parms varchar2) return varchar2;
--    function TO_CHAR(left TIME_TZ_UNCONSTRAINED, format VARCHAR2) return VARCHAR2;
--    function TO_CHAR(left TIME_TZ_UNCONSTRAINED, format VARCHAR2, parms VARCHAR2) return VARCHAR2;
--    function TO_CHAR(left TIME_UNCONSTRAINED, format VARCHAR2) return VARCHAR2;
--    function TO_CHAR(left TIME_UNCONSTRAINED, format VARCHAR2, parms VARCHAR2) return VARCHAR2;
    function TO_CHAR(left TIMESTAMP_LTZ_UNCONSTRAINED, format VARCHAR2) return VARCHAR2;
    function TO_CHAR(left TIMESTAMP_LTZ_UNCONSTRAINED, format VARCHAR2, parms VARCHAR2) return VARCHAR2;
    function TO_CHAR(left TIMESTAMP_TZ_UNCONSTRAINED, format VARCHAR2) return VARCHAR2;
    function TO_CHAR(left TIMESTAMP_TZ_UNCONSTRAINED, format VARCHAR2, parms VARCHAR2) return VARCHAR2;
    function TO_CHAR(left TIMESTAMP_UNCONSTRAINED) return VARCHAR2; -- SS добавлено вручную
    function TO_CHAR(left TIMESTAMP_UNCONSTRAINED, format VARCHAR2) return VARCHAR2;
    function TO_CHAR(left TIMESTAMP_UNCONSTRAINED, format VARCHAR2, parms VARCHAR2) return VARCHAR2;
    function TO_CHAR(left YMINTERVAL_UNCONSTRAINED, format VARCHAR2) return VARCHAR2;
    function TO_CHAR(left YMINTERVAL_UNCONSTRAINED, format VARCHAR2, parms VARCHAR2) return VARCHAR2;
    --function TO_CLOB(cl CLOB) return CLOB;
    function TO_CLOB(RIGHT VARCHAR2) return CLOB;
    function TO_DATE(RIGHT VARCHAR2) return DATE;
    function TO_DATE(LEFT NUMBER, RIGHT VARCHAR2) return DATE;
    function TO_DATE(LEFT VARCHAR2, RIGHT VARCHAR2) return DATE;
    function TO_DATE(left varchar2, format varchar2, parms varchar2) return date;
    function TO_DSINTERVAL(RIGHT varchar2) return DSINTERVAL_UNCONSTRAINED;
    function TO_DSINTERVAL(RIGHT varchar2, parms varchar2) return DSINTERVAL_UNCONSTRAINED;
--    Function TO_LABEL(label VARCHAR2 ) return MLSLABEL;
--    Function TO_LABEL(label VARCHAR2, format VARCHAR2 ) return MLSLABEL;
    function TO_MULTI_BYTE(c VARCHAR2) return VARCHAR2;
    function TO_NCHAR(LEFT DATE, FORMAT NVARCHAR2) return NVARCHAR2;
    function TO_NCHAR(LEFT NUMBER, FORMAT NVARCHAR2) return NVARCHAR2;
    function TO_NCHAR(left binary_double, format nvarchar2) return NVARCHAR2;
    function TO_NCHAR(left binary_double, format nvarchar2, parms nvarchar2) return nvarchar2;
    function TO_NCHAR(left binary_float, format nvarchar2) return NVARCHAR2;
    function TO_NCHAR(left binary_float, format nvarchar2, parms nvarchar2) return nvarchar2;
    function TO_NCHAR(RIGHT NVARCHAR2) return NVARCHAR2;
    --function TO_NCLOB(cl CLOB) return NCLOB;
    function TO_NCLOB(RIGHT VARCHAR2) return NCLOB;
    function TO_NUMBER(RIGHT NUMBER) RETURN NUMBER;
    function TO_NUMBER(RIGHT VARCHAR2) return NUMBER;
    function TO_NUMBER(left varchar2, format varchar2, parms varchar2) return number;
    function TO_NUMBER(left varchar2, format varchar2) return number;
    function TO_RAW(RIGHT BLOB) return RAW;
    function TO_SINGLE_BYTE(c VARCHAR2) return VARCHAR2;
--    function TO_TIME(RIGHT TIME_TZ_UNCONSTRAINED) return TIME_UNCONSTRAINED;
--    function TO_TIME(RIGHT varchar2) return time_unconstrained;
--    function TO_TIME(left varchar2, format varchar2) return TIME_UNCONSTRAINED;
--    function TO_TIME(left varchar2, format varchar2, parms varchar2) return TIME_UNCONSTRAINED;
--    function TO_TIME_TZ(RIGHT TIME_UNCONSTRAINED) return TIME_TZ_UNCONSTRAINED;
--    function TO_TIME_TZ(RIGHT varchar2) return TIME_TZ_UNCONSTRAINED;
--    function TO_TIME_TZ(left varchar2, format varchar2) return TIME_TZ_UNCONSTRAINED;
--    function TO_TIME_TZ(left varchar2, format varchar2, parms varchar2) return TIME_TZ_UNCONSTRAINED;
    function TO_TIMESTAMP(RIGHT DATE) return TIMESTAMP_UNCONSTRAINED;
    function TO_TIMESTAMP(RIGHT TIMESTAMP_TZ_UNCONSTRAINED) return TIMESTAMP_UNCONSTRAINED;
    function TO_TIMESTAMP(RIGHT varchar2) return TIMESTAMP_UNCONSTRAINED;
    function TO_TIMESTAMP(ARG TIMESTAMP_LTZ_UNCONSTRAINED) return TIMESTAMP_UNCONSTRAINED;
    function TO_TIMESTAMP(left varchar2, format varchar2) return TIMESTAMP_UNCONSTRAINED;
    function TO_TIMESTAMP(left varchar2, format varchar2, parms varchar2) return TIMESTAMP_UNCONSTRAINED;
    function TO_TIMESTAMP_TZ(RIGHT TIMESTAMP_UNCONSTRAINED) return TIMESTAMP_TZ_UNCONSTRAINED;
    function TO_TIMESTAMP_TZ(RIGHT varchar2) return TIMESTAMP_TZ_UNCONSTRAINED;
    function TO_TIMESTAMP_TZ(ARG DATE) return TIMESTAMP_TZ_UNCONSTRAINED;
    function TO_TIMESTAMP_TZ(ARG TIMESTAMP_LTZ_UNCONSTRAINED) return TIMESTAMP_TZ_UNCONSTRAINED;
    function TO_TIMESTAMP_TZ(left varchar2, format varchar2) return TIMESTAMP_TZ_UNCONSTRAINED;
    function TO_TIMESTAMP_TZ(left varchar2, format varchar2, parms varchar2) return TIMESTAMP_TZ_UNCONSTRAINED;
    function TO_YMINTERVAL(RIGHT varchar2) return YMINTERVAL_UNCONSTRAINED;
    function TRANSLATE(STR1 VARCHAR2, SRC VARCHAR2, DEST VARCHAR2) return VARCHAR2;
    --function TRIM(v CLOB) return CLOB;
    function TRIM(v VARCHAR2) return VARCHAR2;
    function TRIM(v VARCHAR2, op VARCHAR2) return VARCHAR2;
    function TRIM(v VARCHAR2, chr VARCHAR2, op VARCHAR2) return VARCHAR2;
    function TRUNC(D BINARY_DOUBLE) return BINARY_DOUBLE;
    function TRUNC(F BINARY_FLOAT) return BINARY_FLOAT;
    --function TRUNC(i pls_integer, places pls_integer := 0) return pls_integer;
    function TRUNC(n NUMBER) return NUMBER;
    function TRUNC(n NUMBER, places pls_integer) return NUMBER;
    function TRUNC(LEFT DATE) return DATE;
    function TRUNC(LEFT DATE, RIGHT VARCHAR2) return DATE;
    FUNCTION tz_offset(region VARCHAR2) RETURN VARCHAR2;
    function UID return PLS_INTEGER;
    --function UPPER(ch CLOB) return CLOB; -- to avoid too many
    function UPPER(ch VARCHAR2) return VARCHAR2;
    function USER return VARCHAR2;
    function USERENV(envstr VARCHAR2) return VARCHAR2;
    function ASCII(ch VARCHAR2) return INTEGER;
    function ROWID return ROWID;


    --not actual part of the package
    --function NVL2(expr BOOLEAN, B1 BOOLEAN, B2 BOOLEAN) return BOOLEAN;
    --function NVL2(expr DSINTERVAL_UNCONSTRAINED, b1 DSINTERVAL_UNCONSTRAINED, b2 DSINTERVAL_UNCONSTRAINED) return DSINTERVAL_UNCONSTRAINED;
    --function NVL2(expr TIMESTAMP_LTZ_UNCONSTRAINED, b1 TIMESTAMP_LTZ_UNCONSTRAINED, b2 TIMESTAMP_LTZ_UNCONSTRAINED) return TIMESTAMP_LTZ_UNCONSTRAINED;
    --function NVL2(expr TIMESTAMP_TZ_UNCONSTRAINED, b1 TIMESTAMP_TZ_UNCONSTRAINED, b2 TIMESTAMP_TZ_UNCONSTRAINED) return TIMESTAMP_TZ_UNCONSTRAINED;
    --function NVL2(expr TIMESTAMP_UNCONSTRAINED, b1 TIMESTAMP_UNCONSTRAINED, b2 TIMESTAMP_UNCONSTRAINED) return TIMESTAMP_UNCONSTRAINED;
    --function NVL2(expr YMINTERVAL_UNCONSTRAINED, b1 YMINTERVAL_UNCONSTRAINED, b2 YMINTERVAL_UNCONSTRAINED) return YMINTERVAL_UNCONSTRAINED;
    --function NVL2(expr DATE, d1 DATE, d2 DATE) return DATE;
    --function NVL2(expr BINARY_DOUBLE, d1 BINARY_DOUBLE, d2 BINARY_DOUBLE) return BINARY_DOUBLE;
    --function NVL2(expr BINARY_FLOAT, f1 BINARY_FLOAT, f2 BINARY_FLOAT) return BINARY_FLOAT;
    --function NVL2(expr MLSLABEL, label1 MLSLABEL, label2 MLSLABEL) return MLSLABEL;
    --function NVL2(expr NUMBER, n1 NUMBER, n2 NUMBER) return NUMBER;
    function NVL2(expr VARCHAR2, s1 VARCHAR2, s2 VARCHAR2) return VARCHAR2;

    function  EXTRACT(what VARCHAR2, expr DATE)  return NUMBER;
    -- replace extract with number to extract with interval
    function  EXTRACT(what VARCHAR2, expr NUMBER)  return NUMBER;
    function  EXTRACT(what VARCHAR2, expr TIMESTAMP)  return NUMBER;
    PROCEDURE RAISE_APPLICATION_ERROR (error_number IN NUMBER,error_msg    IN VARCHAR2);
    PROCEDURE RAISE_APPLICATION_ERROR (error_number IN NUMBER,error_msg    IN VARCHAR2, keep_errors  IN BOOLEAN);

    subtype dbms_id is VARCHAR2;
end;
/